# Generated by Django 5.2.6 on 2026-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("reservation_date", models.DateField()),
                (
                    "reservation_slot",
                    models.CharField(
                        choices=[
                            ("19:00", "7:00 PM"),
                            ("19:30", "7:30 PM"),
                            ("20:00", "8:00 PM"),
                            ("20:30", "8:30 PM"),
                            ("21:00", "9:00 PM"),
                            ("21:30", "9:30 PM"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
            options={
                "unique_together": {("reservation_date", "reservation_slot")},
            },
        ),
    ]
